services:
  street-cat-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: street_cat_tracker_app
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      # Canlı kod senkronizasyonu
      - .:/app
      # Host makinenin node_modules klasörünü ezmesini önleyen anonim hacim
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npx expo start --web
